# Generated by Django 4.0.3 on 2022-04-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecomments',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='profilecomments',
            old_name='publish_time',
            new_name='created_on',
        ),
    ]
