# Generated by Django 4.0.3 on 2022-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profilecomments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecomments',
            name='comment_text',
            field=models.TextField(max_length=400),
        ),
    ]
