# Generated by Django 4.0.3 on 2022-04-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profilecomments_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileComments',
        ),
    ]
