services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: django-image
    container_name: django-container
    ports:
      - "8000:8000"
    env_file:
      - "exam_project/.env"
    volumes:
      - .:/project
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - ".env.db"
    volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./data/db:/var/lib/postgresql/data