# Generated by Django 4.0.3 on 2022-04-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_alias'),
        ('comments', '0002_alter_profilecomments_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='profilecomments',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.userprofile'),
        ),
    ]
