# Generated by Django 4.0.3 on 2022-04-07 07:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exam_project.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('alias', models.CharField(blank=True, max_length=25, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), exam_project.utils.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), exam_project.utils.validators.validate_only_letters])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[], default=('Do not show',), max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
